#!/usr/bin/env bash
###############################################################################
# SCMessenger Orchestrator — Startup Script
#
# Runs on first boot (and every reboot) via GCP metadata_startup_script.
# Idempotent — safe to re-run.
#
# What it does:
#   1. Installs system packages (Python 3, git, tmux, sqlite3, jq, gh CLI)
#   2. Creates /opt/scm-orchestrator with a Python virtual environment
#   3. Installs Python dependencies (FastAPI, uvicorn, telegram bot, etc.)
#   4. Writes /etc/scm-orchestrator.env from instance metadata
#   5. Initializes SQLite state database
#   6. Creates and enables a systemd service
###############################################################################
set -euo pipefail

readonly LOG_TAG="scm-orchestrator-startup"
readonly APP_DIR="/opt/scm-orchestrator"
readonly VENV_DIR="${APP_DIR}/venv"
readonly ENV_FILE="/etc/scm-orchestrator.env"
readonly DB_DIR="/var/lib/scm-orchestrator"
readonly DB_FILE="${DB_DIR}/state.db"
readonly SERVICE_NAME="scm-orchestrator"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
log() {
  logger -t "${LOG_TAG}" "$*"
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

# Fetch a value from instance metadata (returns empty string on failure)
metadata() {
  local key="$1"
  curl -sf -H "Metadata-Flavor: Google" \
    "http://metadata.google.internal/computeMetadata/v1/instance/attributes/${key}" 2>/dev/null || true
}

# ---------------------------------------------------------------------------
# 1. System packages
# ---------------------------------------------------------------------------
log "Installing system packages…"
export DEBIAN_FRONTEND=noninteractive

apt-get update -qq
apt-get install -y -qq \
  python3 python3-pip python3-venv \
  git tmux sqlite3 jq curl wget \
  apt-transport-https gnupg

# Install GitHub CLI (gh)
if ! command -v gh &>/dev/null; then
  log "Installing GitHub CLI…"
  curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \
    | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
  chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
    > /etc/apt/sources.list.d/github-cli.list
  apt-get update -qq
  apt-get install -y -qq gh
fi

log "System packages installed."

# ---------------------------------------------------------------------------
# 2. Application directory & Python venv
# ---------------------------------------------------------------------------
log "Setting up application directory and Python venv…"
mkdir -p "${APP_DIR}"

if [ ! -d "${VENV_DIR}" ]; then
  python3 -m venv "${VENV_DIR}"
fi

# Upgrade pip inside the venv
"${VENV_DIR}/bin/pip" install --quiet --upgrade pip

# ---------------------------------------------------------------------------
# 3. Python dependencies
# ---------------------------------------------------------------------------
log "Installing Python dependencies…"
"${VENV_DIR}/bin/pip" install --quiet \
  fastapi \
  "uvicorn[standard]" \
  python-telegram-bot \
  httpx \
  aiosqlite

log "Python dependencies installed."

# ---------------------------------------------------------------------------
# 4. Environment file from instance metadata
# ---------------------------------------------------------------------------
log "Writing environment file from instance metadata…"

TELEGRAM_BOT_TOKEN="$(metadata TELEGRAM_BOT_TOKEN)"
OPENROUTER_API_KEY="$(metadata OPENROUTER_API_KEY)"
GCP_PROJECT="$(metadata GCP_PROJECT)"

cat > "${ENV_FILE}" <<ENVEOF
# SCMessenger Orchestrator — Environment (auto-generated by startup script)
# Last updated: $(date -u '+%Y-%m-%dT%H:%M:%SZ')

TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
GCP_PROJECT=${GCP_PROJECT}
DB_PATH=${DB_FILE}
HOST=0.0.0.0
PORT=8080
ENVEOF

chmod 600 "${ENV_FILE}"
log "Environment file written to ${ENV_FILE}."

# ---------------------------------------------------------------------------
# 5. SQLite database initialisation
# ---------------------------------------------------------------------------
log "Initialising SQLite database…"
mkdir -p "${DB_DIR}"

sqlite3 "${DB_FILE}" <<'SQL'
-- Sprints table: tracks each autonomous work sprint
CREATE TABLE IF NOT EXISTS sprints (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    sprint_id     TEXT    UNIQUE NOT NULL,
    status        TEXT    NOT NULL DEFAULT 'pending',   -- pending|running|success|failed|cancelled
    task_prompt   TEXT    NOT NULL,
    git_branch    TEXT,
    worker_name   TEXT,
    worker_zone   TEXT,
    machine_type  TEXT,
    created_at    TEXT    NOT NULL DEFAULT (datetime('now')),
    started_at    TEXT,
    completed_at  TEXT,
    exit_code     INTEGER,
    result_summary TEXT,
    error_message  TEXT
);

-- Worker heartbeats: periodic health pings from worker VMs
CREATE TABLE IF NOT EXISTS worker_heartbeats (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    sprint_id     TEXT    NOT NULL,
    worker_name   TEXT    NOT NULL,
    status        TEXT    NOT NULL DEFAULT 'alive',     -- alive|busy|idle|shutting_down
    cpu_pct       REAL,
    mem_pct       REAL,
    disk_pct      REAL,
    current_step  TEXT,
    timestamp     TEXT    NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (sprint_id) REFERENCES sprints(sprint_id)
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_sprints_status     ON sprints(status);
CREATE INDEX IF NOT EXISTS idx_sprints_sprint_id  ON sprints(sprint_id);
CREATE INDEX IF NOT EXISTS idx_heartbeats_sprint  ON worker_heartbeats(sprint_id);
CREATE INDEX IF NOT EXISTS idx_heartbeats_time    ON worker_heartbeats(timestamp);
SQL

chmod 644 "${DB_FILE}"
log "SQLite database initialised at ${DB_FILE}."

# ---------------------------------------------------------------------------
# 6. Placeholder app (minimal FastAPI server)
# ---------------------------------------------------------------------------
if [ ! -f "${APP_DIR}/main.py" ]; then
  log "Creating placeholder FastAPI application…"
  cat > "${APP_DIR}/main.py" <<'PYEOF'
"""SCMessenger Orchestrator — FastAPI application (placeholder)."""
import os
from fastapi import FastAPI

app = FastAPI(title="SCMessenger Orchestrator", version="0.1.0")

@app.get("/health")
async def health():
    return {"status": "ok", "service": "scm-orchestrator"}

@app.get("/")
async def root():
    return {"message": "SCMessenger Orchestrator is running"}
PYEOF
fi

# ---------------------------------------------------------------------------
# 7. Systemd service
# ---------------------------------------------------------------------------
log "Creating systemd service…"
cat > "/etc/systemd/system/${SERVICE_NAME}.service" <<SVCEOF
[Unit]
Description=SCMessenger Orchestrator API
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=${APP_DIR}
EnvironmentFile=${ENV_FILE}
ExecStart=${VENV_DIR}/bin/uvicorn main:app --host 0.0.0.0 --port 8080 --log-level info
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

# Hardening
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths=${DB_DIR} ${APP_DIR}

[Install]
WantedBy=multi-user.target
SVCEOF

systemctl daemon-reload
systemctl enable "${SERVICE_NAME}.service"
systemctl restart "${SERVICE_NAME}.service"

log "Systemd service '${SERVICE_NAME}' enabled and started."
log "========== SCMessenger Orchestrator startup complete =========="
