#!/usr/bin/env bash
###############################################################################
# run_aider_sprint.sh — Aider AI Sprint Launcher (tmux)
#
# Starts an Aider session inside a detached tmux session for autonomous coding
# sprints. Output is logged and the session can be monitored in real time.
#
# Usage:
#   ./run_aider_sprint.sh "Implement feature X" [files_to_edit...]
#
# Arguments:
#   $1  — Task prompt (required)
#   $2+ — Files/directories to edit (optional, defaults to core/src/ cli/src/ wasm/src/)
#
# Environment:
#   OPENROUTER_API_KEY — Required for model access
#
# Examples:
#   ./run_aider_sprint.sh "Fix the double-ratchet key derivation bug"
#   ./run_aider_sprint.sh "Add WASM bindings for send_message" wasm/src/lib.rs core/src/api.rs
###############################################################################
set -euo pipefail

# ─── Helpers ────────────────────────────────────────────────────────────────

log() {
  echo "[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] [aider-sprint] $*"
}

die() {
  echo "ERROR: $*" >&2
  exit 1
}

# ─── Arguments ──────────────────────────────────────────────────────────────

TASK_PROMPT="${1:-}"
if [[ -z "$TASK_PROMPT" ]]; then
  die "Usage: $0 <task_prompt> [files_to_edit...]"
fi
shift

# Remaining args are files to edit; default to the main source directories
if [[ $# -gt 0 ]]; then
  FILES_TO_EDIT=("$@")
else
  FILES_TO_EDIT=(core/src/ cli/src/ wasm/src/)
fi

# ─── Validation ─────────────────────────────────────────────────────────────

if [[ -z "${OPENROUTER_API_KEY:-}" ]]; then
  die "OPENROUTER_API_KEY is not set. Export it before running this script."
fi

if ! command -v aider &>/dev/null; then
  die "aider is not installed. Run: pip install aider-chat"
fi

if ! command -v tmux &>/dev/null; then
  die "tmux is not installed."
fi

# ─── Configuration ──────────────────────────────────────────────────────────

readonly TMUX_SESSION="aider-sprint"
readonly AIDER_LOG="/tmp/aider_output.log"
readonly AIDER_MODEL="openrouter/deepseek/deepseek-r1:free"
readonly TEST_CMD="cargo test --workspace 2>&1 | tail -50"

# Find repo root (walk up to find Cargo.toml)
REPO_ROOT="$(pwd)"
while [[ "$REPO_ROOT" != "/" ]]; do
  [[ -f "$REPO_ROOT/Cargo.toml" ]] && break
  REPO_ROOT="$(dirname "$REPO_ROOT")"
done
if [[ ! -f "$REPO_ROOT/Cargo.toml" ]]; then
  die "Could not find Cargo.toml — run this from within the SCMessenger repo"
fi

# Create .aider.conf.yml if it doesn't exist
AIDER_CONF="${REPO_ROOT}/.aider.conf.yml"
if [[ ! -f "$AIDER_CONF" ]]; then
  log "Creating default ${AIDER_CONF}"
  cat > "$AIDER_CONF" <<'CONF_EOF'
# Auto-generated by run_aider_sprint.sh
model: openrouter/deepseek/deepseek-r1:free
weak-model: openrouter/deepseek/deepseek-chat:free
editor-model: openrouter/deepseek/deepseek-r1:free
yes-always: true
auto-commits: false
auto-test: true
test-cmd: 'cargo test --workspace 2>&1 | tail -50'
lint-cmd: 'cargo clippy --workspace -- -D warnings 2>&1 | tail -30'
map-tokens: 2048
map-refresh: auto
read:
  - ARCHITECTURE.md
  - MEMORY.md
  - README.md
CONF_EOF
fi

# ─── Kill Existing Session ──────────────────────────────────────────────────

if tmux has-session -t "$TMUX_SESSION" 2>/dev/null; then
  log "Killing existing tmux session '${TMUX_SESSION}'"
  tmux kill-session -t "$TMUX_SESSION"
fi

# ─── Build File List ────────────────────────────────────────────────────────

# Resolve file arguments relative to repo root
FILE_ARGS=""
for f in "${FILES_TO_EDIT[@]}"; do
  if [[ -e "$REPO_ROOT/$f" ]]; then
    FILE_ARGS+=" $f"
  elif [[ -e "$f" ]]; then
    FILE_ARGS+=" $f"
  else
    log "WARNING: $f does not exist — skipping"
  fi
done

if [[ -z "$FILE_ARGS" ]]; then
  die "No valid files/directories to edit"
fi

# ─── Launch ─────────────────────────────────────────────────────────────────

log "Starting Aider sprint"
log "  Session : ${TMUX_SESSION}"
log "  Model   : ${AIDER_MODEL}"
log "  Files   : ${FILE_ARGS}"
log "  Log     : ${AIDER_LOG}"
log "  Prompt  : ${TASK_PROMPT:0:120}…"

# Build the aider command
AIDER_CMD="cd '${REPO_ROOT}' && aider \
  --message '$(echo "$TASK_PROMPT" | sed "s/'/'\\\\''/g")' \
  --yes-always \
  --auto-test \
  --model '${AIDER_MODEL}' \
  --test-cmd '${TEST_CMD}' \
  ${FILE_ARGS} \
  2>&1 | tee '${AIDER_LOG}'"

# Start detached tmux session
tmux new-session -d -s "$TMUX_SESSION" "$AIDER_CMD"

log "Aider sprint launched in background tmux session."
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  Aider sprint is running in tmux session '${TMUX_SESSION}'      ║"
echo "║                                                              ║"
echo "║  Monitor live:   tmux attach -t ${TMUX_SESSION}              ║"
echo "║  View log:       tail -f ${AIDER_LOG}             ║"
echo "║  Kill session:   tmux kill-session -t ${TMUX_SESSION}        ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
